#cloud-config
write_files:
  - path: /etc/vault.d/bootstrap.sh
    permissions: '0755'
    owner: root
    content: |
      #!/bin/bash
      set -euo pipefail
      export PRIVATE_IP=$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4)
      export AWS_REGION=$(curl -s http://169.254.169.254/latest/dynamic/instance-identity/document | jq -r .region)
      export KMS_KEY_ID="your-kms-key-id"
      envsubst < /etc/vault.d/vault.hcl.template > /etc/vault.d/vault.hcl
      chown vault:vault /etc/vault.d/vault.hcl
      systemctl enable vault
      systemctl restart vault
      for i in {1..20}; do vault status && break || sleep 3; done
      if vault status | grep -q 'not initialized'; then
        vault operator init -key-shares=1 -key-threshold=1 > /root/init.json
      fi

runcmd:
  - [ bash, /etc/vault.d/bootstrap.sh ]
